CREATE OR REPLACE PROCEDURE JRGY_PRO_DELETE_EMPLEADO(
    COD_EMPLEADO_P NUMBER
)
IS
    EXISTE_EMPLEADO NUMBER;
BEGIN
    BEGIN
        SELECT 1 INTO EXISTE_EMPLEADO FROM JRGY_EMPLEADO WHERE COD_EMPLEADO = COD_EMPLEADO_P;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20003, 'El empleado que intenta eliminar no existe.');
    END;

    LOCK TABLE JRGY_EMPLEADO IN ROW EXCLUSIVE MODE;

    DELETE FROM JRGY_EMPLEADO WHERE COD_EMPLEADO = COD_EMPLEADO_P;

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20004, 'Error al eliminar el empleado.');
END;
/