CREATE OR REPLACE PROCEDURE JRGY_PRO_INSERTAR_EMPLEADO(
    CARGO_EMPLEADO_P VARCHAR2,
    FECHA_CONTRATACION_P DATE,
    SALARIO_P NUMBER,
    COMISION_P NUMBER,
    EMAIL_USUARIO_P VARCHAR2,
    COD_MANAGER_P NUMBER DEFAULT NULL
)
IS
    EXISTE_MANAGER NUMBER;
    COD_USUARIO_EMAIL NUMBER;
BEGIN
    BEGIN
        SELECT COD_USUARIO INTO COD_USUARIO_EMAIL FROM JRGY_USUARIO WHERE UPPER(EMAIL_USUARIO) = UPPER(EMAIL_USUARIO_P);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20002, 'El EMAIL_USUARIO proporcionado no existe en la tabla JRGY_USUARIO.');
    END;

    IF COD_MANAGER_P IS NOT NULL THEN
        BEGIN
            SELECT 1 INTO EXISTE_MANAGER FROM JRGY_USUARIO WHERE COD_USUARIO = COD_MANAGER_P;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20001, 'El COD_MANAGER proporcionado no existe como usuario.');
        END;
    END IF;

    LOCK TABLE JRGY_EMPLEADO IN ROW EXCLUSIVE MODE;

    INSERT INTO JRGY_EMPLEADO(COD_EMPLEADO, CARGO_EMPLEADO, FECHA_CONTRATACION, SALARIO, COMISION, COD_USUARIO, COD_MANAGER)
    VALUES(JRGY_SEQ_PK_EMPLEADO.NEXTVAL, CARGO_EMPLEADO_P,  FECHA_CONTRATACION_P, SALARIO_P, COMISION_P, COD_USUARIO_EMAIL, COD_MANAGER_P);

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20004, 'Error al insertar empleado.');
END;
/