CREATE OR REPLACE PROCEDURE JRGY_PRO_UPDATE_EMPLEADO(
    COD_EMPLEADO_P NUMBER,
    CARGO_EMPLEADO_P VARCHAR2,
    FECHA_CONTRATACION_P DATE,
    SALARIO_P NUMBER,
    COMISION_P NUMBER,
    COD_MANAGER_P NUMBER DEFAULT NULL
)
IS
    EXISTE_EMPLEADO NUMBER;
    EXISTE_MANAGER NUMBER;
BEGIN
    BEGIN
        SELECT 1 INTO EXISTE_EMPLEADO FROM JRGY_EMPLEADO WHERE COD_EMPLEADO = COD_EMPLEADO_P;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20010, 'El empleado que intenta actualizar no existe.');
    END;

    IF COD_MANAGER_P IS NOT NULL THEN
        BEGIN
            SELECT 1 INTO EXISTE_MANAGER FROM JRGY_USUARIO WHERE COD_USUARIO = COD_MANAGER_P;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20011, 'El manager indicado no existe como usuario.');
        END;
    END IF;

    LOCK TABLE JRGY_EMPLEADO IN ROW EXCLUSIVE MODE;

    UPDATE JRGY_EMPLEADO 
    SET CARGO_EMPLEADO = CARGO_EMPLEADO_P, FECHA_CONTRATACION = FECHA_CONTRATACION_P, SALARIO = SALARIO_P, COMISION = COMISION_P, COD_MANAGER = COD_MANAGER_P
    WHERE COD_EMPLEADO = COD_EMPLEADO_P;

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20012, 'Error al actualizar el empleado.');
END;
/