CREATE OR REPLACE PROCEDURE JRGY_PRO_DELETE_COMUNA(
    NOMBRE_COMUNA_P VARCHAR2,
    NOMBRE_CIUDAD_P VARCHAR2,
    COD_REGION_P    NUMBER
)
IS
    COD_CIUDAD_AUX     NUMBER;
    COD_REGION_CIUDAD  NUMBER;
    EXISTE_COMUNA      NUMBER;
BEGIN
    LOCK TABLE JRGY_COMUNA IN ROW EXCLUSIVE MODE;

    BEGIN
        SELECT COD_CIUDAD, COD_REGION INTO COD_CIUDAD_AUX, COD_REGION_CIUDAD FROM JRGY_CIUDAD WHERE NOMBRE_CIUDAD = NOMBRE_CIUDAD_P;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20001, 'La ciudad no existe.');
    END;

    IF COD_REGION_CIUDAD != COD_REGION_P THEN
        RAISE_APPLICATION_ERROR(-20002, 'La ciudad no pertenece a la región ingresada.');
    END IF;

    BEGIN
        SELECT 1 INTO EXISTE_COMUNA FROM JRGY_COMUNA WHERE NOMBRE_COMUNA = NOMBRE_COMUNA_P AND COD_CIUDAD = COD_CIUDAD_AUX;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20003,
                'La comuna no existe en la ciudad especificada.');
    END;

    DELETE FROM JRGY_COMUNA WHERE NOMBRE_COMUNA = NOMBRE_COMUNA_P AND COD_CIUDAD = COD_CIUDAD_AUX;

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20004, 'Error al eliminar la comuna.');
END;
/
