CREATE OR REPLACE PROCEDURE JRGY_PRO_DELETE_REGION(
    COD_REGION_P NUMBER
)
IS
    REGION_EXISTE NUMBER;
BEGIN
    LOCK TABLE JRGY_REGION IN ROW EXCLUSIVE MODE;

    BEGIN
        SELECT 1 INTO REGION_EXISTE FROM JRGY_REGION WHERE COD_REGION = COD_REGION_P;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20010, 'La region proporcionada no existe.');
    END;

    DELETE FROM JRGY_REGION WHERE COD_REGION = COD_REGION_P;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20011, 'Error al eliminar region.');
END;
/