CREATE OR REPLACE PROCEDURE JRGY_PRO_INSERTAR_REGION(
    NOMBRE_REGION_P VARCHAR2
)
IS
    REGION_EXISTE NUMBER;
BEGIN
    LOCK TABLE JRGY_REGION IN ROW EXCLUSIVE MODE;

    BEGIN
        SELECT 1 INTO REGION_EXISTE FROM JRGY_REGION WHERE NOMBRE_REGION = NOMBRE_REGION_P;
            RAISE_APPLICATION_ERROR(-20003, 'La region proporcionada ya existe.');
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                NULL;
    END;

    INSERT INTO JRGY_REGION(COD_REGION, NOMBRE_REGION) 
    VALUES(JRGY_SEQ_PK_REGION.NEXTVAL, NOMBRE_REGION_P);
    COMMIT;

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20005, 'Error al insertar region.');

END;
/