CREATE OR REPLACE PROCEDURE JRGY_PRO_UPDATE_REGION(
    COD_REGION_P NUMBER,
    NOMBRE_REGION_P VARCHAR2
)
IS
    REGION_EXISTE NUMBER;
BEGIN
    LOCK TABLE JRGY_REGION IN ROW EXCLUSIVE MODE;

    BEGIN
        SELECT 1 INTO REGION_EXISTE FROM JRGY_REGION WHERE COD_REGION = COD_REGION_P;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20006, 'La region proporcionada no existe.');
    END;

    UPDATE JRGY_REGION SET NOMBRE_REGION = NOMBRE_REGION_P
    WHERE COD_REGION = COD_REGION_P;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE_APPLICATION_ERROR(-20007, 'Error al actualizar region.');
END;
/