CREATE OR REPLACE PROCEDURE JRGY_PRO_DELETE_CALLE(
    NOMBRE_CALLE_P VARCHAR2,
    NRO_CALLE_P NUMBER,
    NOMBRE_COMUNA_P VARCHAR2,
    NOMBRE_CIUDAD_P VARCHAR2,
    COD_REGION_P NUMBER
)
IS
   COD_COMUNA_AUX NUMBER;
   COD_CIUDAD_AUX NUMBER;
   COD_CIUDAD_COMUNA NUMBER;
   COD_REGION_CIUDAD NUMBER;
   CALLE_EXISTE NUMBER;
BEGIN
    LOCK TABLE JRGY_CALLE IN ROW EXCLUSIVE MODE;

    BEGIN
        SELECT COD_CIUDAD, COD_REGION INTO COD_CIUDAD_AUX, COD_REGION_CIUDAD FROM JRGY_CIUDAD WHERE UPPER(NOMBRE_CIUDAD) = UPPER(NOMBRE_CIUDAD_P);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20001, 'La ciudad no existe.');
    END;

    IF COD_REGION_CIUDAD != COD_REGION_P THEN
        RAISE_APPLICATION_ERROR(-20002, 'La ciudad no pertenece a la región ingresada.');
    END IF;

    BEGIN
        SELECT COD_COMUNA, COD_CIUDAD INTO COD_COMUNA_AUX, COD_CIUDAD_COMUNA FROM JRGY_COMUNA WHERE UPPER(NOMBRE_COMUNA) = UPPER(NOMBRE_COMUNA_P);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20003, 'La comuna no existe.');
    END;

    IF COD_CIUDAD_COMUNA != COD_CIUDAD_AUX THEN
        RAISE_APPLICATION_ERROR(-20004, 'La comuna no pertenece a la ciudad ingresada.');
    END IF;

    BEGIN
        SELECT 1 INTO CALLE_EXISTE FROM JRGY_CALLE WHERE UPPER(NOMBRE_CALLE) = UPPER(NOMBRE_CALLE_P) AND NRO_CALLE = NRO_CALLE_P AND COD_COMUNA = COD_COMUNA_AUX;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20005, 'La calle no existe en la comuna especificada.');
    END;

    DELETE FROM JRGY_CALLE WHERE UPPER(NOMBRE_CALLE) = UPPER(NOMBRE_CALLE_P) AND NRO_CALLE = NRO_CALLE_P AND COD_COMUNA = COD_COMUNA_AUX;

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20006, 'Error al eliminar la calle.');
END;
/