CREATE OR REPLACE PROCEDURE JRGY_PRO_UPDATE_CALLE(
    NOMBRE_CALLE_P VARCHAR2,
    NRO_CALLE_P NUMBER,
    NOMBRE_NUEVO_P VARCHAR2,
    NRO_NUEVO_P NUMBER,
    NOMBRE_COMUNA_P VARCHAR2,
    NOMBRE_CIUDAD_P VARCHAR2,
    COD_REGION_P NUMBER
)
IS
    COD_COMUNA_AUX NUMBER;
    COD_CIUDAD_AUX NUMBER;
    COD_REGION_CIUDAD NUMBER;
    COD_CIUDAD_COMUNA NUMBER;
    CALLE_EXISTE NUMBER;
BEGIN
    LOCK TABLE JRGY_CALLE IN ROW EXCLUSIVE MODE;

    BEGIN
        SELECT 1 INTO CALLE_EXISTE FROM JRGY_CALLE WHERE UPPER(NOMBRE_CALLE) = UPPER(NOMBRE_CALLE_P) AND NRO_CALLE = NRO_CALLE_P;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20006, 'La calle proporcionada no existe.');
    END;

    BEGIN
        SELECT COD_COMUNA, COD_CIUDAD INTO COD_COMUNA_AUX, COD_CIUDAD_COMUNA FROM JRGY_COMUNA WHERE UPPER(NOMBRE_COMUNA) = UPPER(NOMBRE_COMUNA_P);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20007, 'La comuna proporcionada no existe.');
    END;

    BEGIN
        SELECT COD_CIUDAD, COD_REGION INTO COD_CIUDAD_AUX, COD_REGION_CIUDAD FROM JRGY_CIUDAD WHERE UPPER(NOMBRE_CIUDAD) = UPPER(NOMBRE_CIUDAD_P);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20008, 'La ciudad proporcionada no existe.');      
    END;

    IF COD_REGION_CIUDAD != COD_REGION_P THEN
        RAISE_APPLICATION_ERROR(-20004, 'La ciudad no pertenece a la region proporcionada.');
    END IF;

    IF COD_CIUDAD_COMUNA != COD_CIUDAD_AUX THEN
        RAISE_APPLICATION_ERROR(-20005, 'La comuna no pertenece a la ciudad proporcionada.');
    END IF;

    UPDATE JRGY_CALLE
    SET NOMBRE_CALLE = NOMBRE_NUEVO_P, NRO_CALLE = NRO_NUEVO_P, COD_COMUNA = COD_COMUNA_AUX
    WHERE UPPER(NOMBRE_CALLE) = UPPER(NOMBRE_CALLE_P) AND NRO_CALLE = NRO_CALLE_P;

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20009, 'Error al actualizar la calle.');
END;
/