CREATE OR REPLACE PROCEDURE JRGY_PRO_INSERTAR_CALLE(
    NOMBRE_CALLE_P VARCHAR2,
    NRO_CALLE_P NUMBER,
    NOMBRE_COMUNA_P VARCHAR2,
    NOMBRE_CIUDAD_P VARCHAR2,
    COD_REGION_P NUMBER
)
IS
    COD_COMUNA_AUX NUMBER;
    COD_CIUDAD_AUX NUMBER;
    CALLE_EXISTE NUMBER;
    COD_REGION_CIUDAD NUMBER;
    COD_CIUDAD_COMUNA NUMBER;
BEGIN
    LOCK TABLE JRGY_CALLE IN ROW EXCLUSIVE MODE;

    BEGIN
        SELECT 1 INTO CALLE_EXISTE FROM JRGY_CALLE WHERE UPPER(NOMBRE_CALLE) = UPPER(NOMBRE_CALLE_P) AND NRO_CALLE = NRO_CALLE_P;
            RAISE_APPLICATION_ERROR(-20006, 'La calle proporcionada ya existe.');
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                NULL;
    END;

    BEGIN
        SELECT COD_COMUNA, COD_CIUDAD INTO COD_COMUNA_AUX, COD_CIUDAD_COMUNA FROM JRGY_COMUNA WHERE UPPER(NOMBRE_COMUNA) = UPPER(NOMBRE_COMUNA_P);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20007, 'La comuna proporcionada no existe.');
    END;

    BEGIN
        SELECT COD_CIUDAD, COD_REGION INTO COD_CIUDAD_AUX, COD_REGION_CIUDAD FROM JRGY_CIUDAD 
        WHERE UPPER(NOMBRE_CIUDAD) = UPPER(NOMBRE_CIUDAD_P);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20008, 'La ciudad proporcionada no existe.');

    END;

    IF COD_REGION_CIUDAD != COD_REGION_P THEN
        RAISE_APPLICATION_ERROR(-20009, 'La ciudad no pertenece a la region proporcionada.');
    END IF;

    IF COD_CIUDAD_COMUNA != COD_CIUDAD_AUX THEN
        RAISE_APPLICATION_ERROR(-20010, 'La comuna no pertenece a la ciudad proporcionada.');
    END IF;

    INSERT INTO JRGY_CALLE(COD_CALLE, NOMBRE_CALLE, NRO_CALLE, COD_COMUNA)
    VALUES(JRGY_SEQ_PK_CALLE.NEXTVAL, NOMBRE_CALLE_P, NRO_CALLE_P, COD_COMUNA_AUX);

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20004, 'Error al insertar la calle.');
END;
/