CREATE OR REPLACE PROCEDURE JRGY_PRO_UPDATE_CIUDAD(
    NOMBRE_ACTUAL_P VARCHAR2,
    NOMBRE_NUEVO_P  VARCHAR2,
    COD_REGION_P    NUMBER
)
IS
    EXISTE_CIUDAD NUMBER;
    EXISTE_REGION NUMBER;
BEGIN
    LOCK TABLE JRGY_CIUDAD IN ROW EXCLUSIVE MODE;

    BEGIN
        SELECT 1 INTO EXISTE_CIUDAD FROM JRGY_CIUDAD WHERE NOMBRE_CIUDAD = NOMBRE_ACTUAL_P;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20001, 'La ciudad no existe en el sistema.');
    END;

    -- Validar región
    BEGIN
        SELECT 1 INTO EXISTE_REGION FROM JRGY_REGION WHERE COD_REGION = COD_REGION_P;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20002, 'La región especificada no existe.');
    END;

    UPDATE JRGY_CIUDAD SET NOMBRE_CIUDAD = NOMBRE_NUEVO_P,COD_REGION = COD_REGION_P
    WHERE NOMBRE_CIUDAD = NOMBRE_ACTUAL_P;

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20003, 'Error al actualizar la ciudad.');
END;
/
