CREATE OR REPLACE PROCEDURE JRGY_PRO_DELETE_CIUDAD(
    NOMBRE_CIUDAD_P VARCHAR2,
    COD_REGION_P    NUMBER
)
IS
    CIUDAD_EXISTE NUMBER;
BEGIN
    LOCK TABLE JRGY_CIUDAD IN ROW EXCLUSIVE MODE;

    BEGIN
        SELECT 1 INTO CIUDAD_EXISTE FROM JRGY_CIUDAD WHERE NOMBRE_CIUDAD = NOMBRE_CIUDAD_P AND COD_REGION = COD_REGION_P;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20020, 'La ciudad indicada no existe en esa región.');
    END;

    DELETE FROM JRGY_CIUDAD WHERE NOMBRE_CIUDAD = NOMBRE_CIUDAD_P AND COD_REGION = COD_REGION_P;
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20021, 'Error al eliminar la ciudad.');
END;
/
