CREATE OR REPLACE PROCEDURE JRGY_PRO_INSERTAR_CIUDAD(
    NOMBRE_CIUDAD_P VARCHAR2,
    COD_REGION_P NUMBER
)
IS
    EXISTE_CIUDAD NUMBER;
    EXISTE_REGION NUMBER;
BEGIN
    LOCK TABLE JRGY_CIUDAD IN ROW EXCLUSIVE MODE;

    BEGIN
        SELECT 1 INTO EXISTE_CIUDAD FROM JRGY_CIUDAD WHERE NOMBRE_CIUDAD =  NOMBRE_CIUDAD_P;
        RAISE_APPLICATION_ERROR(-20001, 'La ciudad ya existe en el sistema.');
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            NULL;
    END;

    BEGIN
        SELECT 1 INTO EXISTE_REGION  FROM JRGY_REGION WHERE COD_REGION = COD_REGION_P;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20002, 'La región especificada no existe.');
    END;

        INSERT INTO JRGY_CIUDAD(COD_CIUDAD, NOMBRE_CIUDAD, COD_REGION)
        VALUES(JRGY_SEQ_PK_CIUDAD.NEXTVAL, NOMBRE_CIUDAD_P, COD_REGION_P);
        COMMIT;

        EXCEPTION
            WHEN OTHERS THEN
                ROLLBACK;
                RAISE_APPLICATION_ERROR(-20003, 'Error al insertar la ciudad.');
END;
/